// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                        = new(Query)
	RecordAnalysisJob        *recordAnalysisJob
	RecordAnalysisJobEvent   *recordAnalysisJobEvent
	RecordAnalysisJobMessage *recordAnalysisJobMessage
	RecordAnalysisRecord     *recordAnalysisRecord
	RecordAnalysisSession    *recordAnalysisSession
	RecordAnalysisUser       *recordAnalysisUser
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	RecordAnalysisJob = &Q.RecordAnalysisJob
	RecordAnalysisJobEvent = &Q.RecordAnalysisJobEvent
	RecordAnalysisJobMessage = &Q.RecordAnalysisJobMessage
	RecordAnalysisRecord = &Q.RecordAnalysisRecord
	RecordAnalysisSession = &Q.RecordAnalysisSession
	RecordAnalysisUser = &Q.RecordAnalysisUser
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                       db,
		RecordAnalysisJob:        newRecordAnalysisJob(db, opts...),
		RecordAnalysisJobEvent:   newRecordAnalysisJobEvent(db, opts...),
		RecordAnalysisJobMessage: newRecordAnalysisJobMessage(db, opts...),
		RecordAnalysisRecord:     newRecordAnalysisRecord(db, opts...),
		RecordAnalysisSession:    newRecordAnalysisSession(db, opts...),
		RecordAnalysisUser:       newRecordAnalysisUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	RecordAnalysisJob        recordAnalysisJob
	RecordAnalysisJobEvent   recordAnalysisJobEvent
	RecordAnalysisJobMessage recordAnalysisJobMessage
	RecordAnalysisRecord     recordAnalysisRecord
	RecordAnalysisSession    recordAnalysisSession
	RecordAnalysisUser       recordAnalysisUser
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                       db,
		RecordAnalysisJob:        q.RecordAnalysisJob.clone(db),
		RecordAnalysisJobEvent:   q.RecordAnalysisJobEvent.clone(db),
		RecordAnalysisJobMessage: q.RecordAnalysisJobMessage.clone(db),
		RecordAnalysisRecord:     q.RecordAnalysisRecord.clone(db),
		RecordAnalysisSession:    q.RecordAnalysisSession.clone(db),
		RecordAnalysisUser:       q.RecordAnalysisUser.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                       db,
		RecordAnalysisJob:        q.RecordAnalysisJob.replaceDB(db),
		RecordAnalysisJobEvent:   q.RecordAnalysisJobEvent.replaceDB(db),
		RecordAnalysisJobMessage: q.RecordAnalysisJobMessage.replaceDB(db),
		RecordAnalysisRecord:     q.RecordAnalysisRecord.replaceDB(db),
		RecordAnalysisSession:    q.RecordAnalysisSession.replaceDB(db),
		RecordAnalysisUser:       q.RecordAnalysisUser.replaceDB(db),
	}
}

type queryCtx struct {
	RecordAnalysisJob        IRecordAnalysisJobDo
	RecordAnalysisJobEvent   IRecordAnalysisJobEventDo
	RecordAnalysisJobMessage IRecordAnalysisJobMessageDo
	RecordAnalysisRecord     IRecordAnalysisRecordDo
	RecordAnalysisSession    IRecordAnalysisSessionDo
	RecordAnalysisUser       IRecordAnalysisUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		RecordAnalysisJob:        q.RecordAnalysisJob.WithContext(ctx),
		RecordAnalysisJobEvent:   q.RecordAnalysisJobEvent.WithContext(ctx),
		RecordAnalysisJobMessage: q.RecordAnalysisJobMessage.WithContext(ctx),
		RecordAnalysisRecord:     q.RecordAnalysisRecord.WithContext(ctx),
		RecordAnalysisSession:    q.RecordAnalysisSession.WithContext(ctx),
		RecordAnalysisUser:       q.RecordAnalysisUser.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
