// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/kevinmatthe/record_analysis/internal/infrastructure/db/model"
)

func newRecordAnalysisSession(db *gorm.DB, opts ...gen.DOOption) recordAnalysisSession {
	_recordAnalysisSession := recordAnalysisSession{}

	_recordAnalysisSession.recordAnalysisSessionDo.IWithDO = gen.WithDOFunc[IRecordAnalysisSessionDo](_recordAnalysisSession.recordAnalysisSessionDo.withDO)

	_recordAnalysisSession.recordAnalysisSessionDo.UseDB(db, opts...)
	_recordAnalysisSession.recordAnalysisSessionDo.UseModel(&model.RecordAnalysisSession{})

	tableName := _recordAnalysisSession.recordAnalysisSessionDo.TableName()
	_recordAnalysisSession.ALL = field.NewAsterisk(tableName)
	_recordAnalysisSession.Token = field.NewString(tableName, "token")
	_recordAnalysisSession.Username = field.NewString(tableName, "username")
	_recordAnalysisSession.ExpiresAt = field.NewTime(tableName, "expires_at")
	_recordAnalysisSession.CreatedAt = field.NewTime(tableName, "created_at")

	_recordAnalysisSession.fillFieldMap()

	return _recordAnalysisSession
}

type recordAnalysisSession struct {
	recordAnalysisSessionDo recordAnalysisSessionDo

	ALL       field.Asterisk
	Token     field.String
	Username  field.String
	ExpiresAt field.Time
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (r recordAnalysisSession) Table(newTableName string) *recordAnalysisSession {
	r.recordAnalysisSessionDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r recordAnalysisSession) As(alias string) *recordAnalysisSession {
	r.recordAnalysisSessionDo.DO = *(r.recordAnalysisSessionDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *recordAnalysisSession) updateTableName(table string) *recordAnalysisSession {
	r.ALL = field.NewAsterisk(table)
	r.Token = field.NewString(table, "token")
	r.Username = field.NewString(table, "username")
	r.ExpiresAt = field.NewTime(table, "expires_at")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *recordAnalysisSession) WithContext(ctx context.Context) IRecordAnalysisSessionDo {
	return r.recordAnalysisSessionDo.WithContext(ctx)
}

func (r recordAnalysisSession) TableName() string { return r.recordAnalysisSessionDo.TableName() }

func (r recordAnalysisSession) Alias() string { return r.recordAnalysisSessionDo.Alias() }

func (r recordAnalysisSession) Columns(cols ...field.Expr) gen.Columns {
	return r.recordAnalysisSessionDo.Columns(cols...)
}

func (r *recordAnalysisSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *recordAnalysisSession) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["token"] = r.Token
	r.fieldMap["username"] = r.Username
	r.fieldMap["expires_at"] = r.ExpiresAt
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r recordAnalysisSession) clone(db *gorm.DB) recordAnalysisSession {
	r.recordAnalysisSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r recordAnalysisSession) replaceDB(db *gorm.DB) recordAnalysisSession {
	r.recordAnalysisSessionDo.ReplaceDB(db)
	return r
}

type recordAnalysisSessionDo struct {
	gen.GenericsDo[IRecordAnalysisSessionDo, *model.RecordAnalysisSession]
}
type IRecordAnalysisSessionDo interface {
	gen.IGenericsDo[IRecordAnalysisSessionDo, *model.RecordAnalysisSession]
}

func (r *recordAnalysisSessionDo) withDO(do gen.Dao) IRecordAnalysisSessionDo {
	_r := &recordAnalysisSessionDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRecordAnalysisSessionDo](r.withDO)
	return _r
}
