// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/kevinmatthe/record_analysis/internal/infrastructure/db/model"
)

func newRecordAnalysisRecord(db *gorm.DB, opts ...gen.DOOption) recordAnalysisRecord {
	_recordAnalysisRecord := recordAnalysisRecord{}

	_recordAnalysisRecord.recordAnalysisRecordDo.IWithDO = gen.WithDOFunc[IRecordAnalysisRecordDo](_recordAnalysisRecord.recordAnalysisRecordDo.withDO)

	_recordAnalysisRecord.recordAnalysisRecordDo.UseDB(db, opts...)
	_recordAnalysisRecord.recordAnalysisRecordDo.UseModel(&model.RecordAnalysisRecord{})

	tableName := _recordAnalysisRecord.recordAnalysisRecordDo.TableName()
	_recordAnalysisRecord.ALL = field.NewAsterisk(tableName)
	_recordAnalysisRecord.ID = field.NewString(tableName, "id")
	_recordAnalysisRecord.RelationshipID = field.NewString(tableName, "relationship_id")
	_recordAnalysisRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_recordAnalysisRecord.PeriodStart = field.NewTime(tableName, "period_start")
	_recordAnalysisRecord.PeriodEnd = field.NewTime(tableName, "period_end")
	_recordAnalysisRecord.MessageCount = field.NewInt64(tableName, "message_count")
	_recordAnalysisRecord.ActionCount = field.NewInt64(tableName, "action_count")
	_recordAnalysisRecord.EventCount = field.NewInt64(tableName, "event_count")
	_recordAnalysisRecord.ModelName = field.NewString(tableName, "model_name")
	_recordAnalysisRecord.ObjectKey = field.NewString(tableName, "object_key")
	_recordAnalysisRecord.ObjectURI = field.NewString(tableName, "object_uri")
	_recordAnalysisRecord.ReportPath = field.NewString(tableName, "report_path")
	_recordAnalysisRecord.Status = field.NewString(tableName, "status")

	_recordAnalysisRecord.fillFieldMap()

	return _recordAnalysisRecord
}

type recordAnalysisRecord struct {
	recordAnalysisRecordDo recordAnalysisRecordDo

	ALL            field.Asterisk
	ID             field.String
	RelationshipID field.String
	CreatedAt      field.Time
	PeriodStart    field.Time
	PeriodEnd      field.Time
	MessageCount   field.Int64
	ActionCount    field.Int64
	EventCount     field.Int64
	ModelName      field.String
	ObjectKey      field.String
	ObjectURI      field.String
	ReportPath     field.String
	Status         field.String

	fieldMap map[string]field.Expr
}

func (r recordAnalysisRecord) Table(newTableName string) *recordAnalysisRecord {
	r.recordAnalysisRecordDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r recordAnalysisRecord) As(alias string) *recordAnalysisRecord {
	r.recordAnalysisRecordDo.DO = *(r.recordAnalysisRecordDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *recordAnalysisRecord) updateTableName(table string) *recordAnalysisRecord {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.RelationshipID = field.NewString(table, "relationship_id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.PeriodStart = field.NewTime(table, "period_start")
	r.PeriodEnd = field.NewTime(table, "period_end")
	r.MessageCount = field.NewInt64(table, "message_count")
	r.ActionCount = field.NewInt64(table, "action_count")
	r.EventCount = field.NewInt64(table, "event_count")
	r.ModelName = field.NewString(table, "model_name")
	r.ObjectKey = field.NewString(table, "object_key")
	r.ObjectURI = field.NewString(table, "object_uri")
	r.ReportPath = field.NewString(table, "report_path")
	r.Status = field.NewString(table, "status")

	r.fillFieldMap()

	return r
}

func (r *recordAnalysisRecord) WithContext(ctx context.Context) IRecordAnalysisRecordDo {
	return r.recordAnalysisRecordDo.WithContext(ctx)
}

func (r recordAnalysisRecord) TableName() string { return r.recordAnalysisRecordDo.TableName() }

func (r recordAnalysisRecord) Alias() string { return r.recordAnalysisRecordDo.Alias() }

func (r recordAnalysisRecord) Columns(cols ...field.Expr) gen.Columns {
	return r.recordAnalysisRecordDo.Columns(cols...)
}

func (r *recordAnalysisRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *recordAnalysisRecord) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 13)
	r.fieldMap["id"] = r.ID
	r.fieldMap["relationship_id"] = r.RelationshipID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["period_start"] = r.PeriodStart
	r.fieldMap["period_end"] = r.PeriodEnd
	r.fieldMap["message_count"] = r.MessageCount
	r.fieldMap["action_count"] = r.ActionCount
	r.fieldMap["event_count"] = r.EventCount
	r.fieldMap["model_name"] = r.ModelName
	r.fieldMap["object_key"] = r.ObjectKey
	r.fieldMap["object_uri"] = r.ObjectURI
	r.fieldMap["report_path"] = r.ReportPath
	r.fieldMap["status"] = r.Status
}

func (r recordAnalysisRecord) clone(db *gorm.DB) recordAnalysisRecord {
	r.recordAnalysisRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r recordAnalysisRecord) replaceDB(db *gorm.DB) recordAnalysisRecord {
	r.recordAnalysisRecordDo.ReplaceDB(db)
	return r
}

type recordAnalysisRecordDo struct {
	gen.GenericsDo[IRecordAnalysisRecordDo, *model.RecordAnalysisRecord]
}
type IRecordAnalysisRecordDo interface {
	gen.IGenericsDo[IRecordAnalysisRecordDo, *model.RecordAnalysisRecord]
}

func (r *recordAnalysisRecordDo) withDO(do gen.Dao) IRecordAnalysisRecordDo {
	_r := &recordAnalysisRecordDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRecordAnalysisRecordDo](r.withDO)
	return _r
}
