// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/kevinmatthe/record_analysis/internal/infrastructure/db/model"
)

func newRecordAnalysisJobEvent(db *gorm.DB, opts ...gen.DOOption) recordAnalysisJobEvent {
	_recordAnalysisJobEvent := recordAnalysisJobEvent{}

	_recordAnalysisJobEvent.recordAnalysisJobEventDo.IWithDO = gen.WithDOFunc[IRecordAnalysisJobEventDo](_recordAnalysisJobEvent.recordAnalysisJobEventDo.withDO)

	_recordAnalysisJobEvent.recordAnalysisJobEventDo.UseDB(db, opts...)
	_recordAnalysisJobEvent.recordAnalysisJobEventDo.UseModel(&model.RecordAnalysisJobEvent{})

	tableName := _recordAnalysisJobEvent.recordAnalysisJobEventDo.TableName()
	_recordAnalysisJobEvent.ALL = field.NewAsterisk(tableName)
	_recordAnalysisJobEvent.ID = field.NewInt64(tableName, "id")
	_recordAnalysisJobEvent.JobID = field.NewString(tableName, "job_id")
	_recordAnalysisJobEvent.Message = field.NewString(tableName, "message")
	_recordAnalysisJobEvent.CreatedAt = field.NewTime(tableName, "created_at")

	_recordAnalysisJobEvent.fillFieldMap()

	return _recordAnalysisJobEvent
}

type recordAnalysisJobEvent struct {
	recordAnalysisJobEventDo recordAnalysisJobEventDo

	ALL       field.Asterisk
	ID        field.Int64
	JobID     field.String
	Message   field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (r recordAnalysisJobEvent) Table(newTableName string) *recordAnalysisJobEvent {
	r.recordAnalysisJobEventDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r recordAnalysisJobEvent) As(alias string) *recordAnalysisJobEvent {
	r.recordAnalysisJobEventDo.DO = *(r.recordAnalysisJobEventDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *recordAnalysisJobEvent) updateTableName(table string) *recordAnalysisJobEvent {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.JobID = field.NewString(table, "job_id")
	r.Message = field.NewString(table, "message")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *recordAnalysisJobEvent) WithContext(ctx context.Context) IRecordAnalysisJobEventDo {
	return r.recordAnalysisJobEventDo.WithContext(ctx)
}

func (r recordAnalysisJobEvent) TableName() string { return r.recordAnalysisJobEventDo.TableName() }

func (r recordAnalysisJobEvent) Alias() string { return r.recordAnalysisJobEventDo.Alias() }

func (r recordAnalysisJobEvent) Columns(cols ...field.Expr) gen.Columns {
	return r.recordAnalysisJobEventDo.Columns(cols...)
}

func (r *recordAnalysisJobEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *recordAnalysisJobEvent) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["id"] = r.ID
	r.fieldMap["job_id"] = r.JobID
	r.fieldMap["message"] = r.Message
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r recordAnalysisJobEvent) clone(db *gorm.DB) recordAnalysisJobEvent {
	r.recordAnalysisJobEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r recordAnalysisJobEvent) replaceDB(db *gorm.DB) recordAnalysisJobEvent {
	r.recordAnalysisJobEventDo.ReplaceDB(db)
	return r
}

type recordAnalysisJobEventDo struct {
	gen.GenericsDo[IRecordAnalysisJobEventDo, *model.RecordAnalysisJobEvent]
}
type IRecordAnalysisJobEventDo interface {
	gen.IGenericsDo[IRecordAnalysisJobEventDo, *model.RecordAnalysisJobEvent]
}

func (r *recordAnalysisJobEventDo) withDO(do gen.Dao) IRecordAnalysisJobEventDo {
	_r := &recordAnalysisJobEventDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRecordAnalysisJobEventDo](r.withDO)
	return _r
}
