// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/kevinmatthe/record_analysis/internal/infrastructure/db/model"
)

func newRecordAnalysisJob(db *gorm.DB, opts ...gen.DOOption) recordAnalysisJob {
	_recordAnalysisJob := recordAnalysisJob{}

	_recordAnalysisJob.recordAnalysisJobDo.IWithDO = gen.WithDOFunc[IRecordAnalysisJobDo](_recordAnalysisJob.recordAnalysisJobDo.withDO)

	_recordAnalysisJob.recordAnalysisJobDo.UseDB(db, opts...)
	_recordAnalysisJob.recordAnalysisJobDo.UseModel(&model.RecordAnalysisJob{})

	tableName := _recordAnalysisJob.recordAnalysisJobDo.TableName()
	_recordAnalysisJob.ALL = field.NewAsterisk(tableName)
	_recordAnalysisJob.ID = field.NewString(tableName, "id")
	_recordAnalysisJob.Status = field.NewString(tableName, "status")
	_recordAnalysisJob.Stage = field.NewString(tableName, "stage")
	_recordAnalysisJob.RelationshipID = field.NewString(tableName, "relationship_id")
	_recordAnalysisJob.FileName = field.NewString(tableName, "file_name")
	_recordAnalysisJob.MessageCount = field.NewInt64(tableName, "message_count")
	_recordAnalysisJob.LlmMessageLimit = field.NewInt64(tableName, "llm_message_limit")
	_recordAnalysisJob.LlmMessageCount = field.NewInt64(tableName, "llm_message_count")
	_recordAnalysisJob.ProcessedCount = field.NewInt64(tableName, "processed_count")
	_recordAnalysisJob.Progress = field.NewFloat64(tableName, "progress")
	_recordAnalysisJob.PreviewTotal = field.NewInt64(tableName, "preview_total")
	_recordAnalysisJob.ResultRecordID = field.NewString(tableName, "result_record_id")
	_recordAnalysisJob.Error = field.NewString(tableName, "error")
	_recordAnalysisJob.CreatedAt = field.NewTime(tableName, "created_at")
	_recordAnalysisJob.UpdatedAt = field.NewTime(tableName, "updated_at")
	_recordAnalysisJob.AnalysisMode = field.NewString(tableName, "analysis_mode")

	_recordAnalysisJob.fillFieldMap()

	return _recordAnalysisJob
}

type recordAnalysisJob struct {
	recordAnalysisJobDo recordAnalysisJobDo

	ALL             field.Asterisk
	ID              field.String
	Status          field.String
	Stage           field.String
	RelationshipID  field.String
	FileName        field.String
	MessageCount    field.Int64
	LlmMessageLimit field.Int64
	LlmMessageCount field.Int64
	ProcessedCount  field.Int64
	Progress        field.Float64
	PreviewTotal    field.Int64
	ResultRecordID  field.String
	Error           field.String
	CreatedAt       field.Time
	UpdatedAt       field.Time
	AnalysisMode    field.String

	fieldMap map[string]field.Expr
}

func (r recordAnalysisJob) Table(newTableName string) *recordAnalysisJob {
	r.recordAnalysisJobDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r recordAnalysisJob) As(alias string) *recordAnalysisJob {
	r.recordAnalysisJobDo.DO = *(r.recordAnalysisJobDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *recordAnalysisJob) updateTableName(table string) *recordAnalysisJob {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.Status = field.NewString(table, "status")
	r.Stage = field.NewString(table, "stage")
	r.RelationshipID = field.NewString(table, "relationship_id")
	r.FileName = field.NewString(table, "file_name")
	r.MessageCount = field.NewInt64(table, "message_count")
	r.LlmMessageLimit = field.NewInt64(table, "llm_message_limit")
	r.LlmMessageCount = field.NewInt64(table, "llm_message_count")
	r.ProcessedCount = field.NewInt64(table, "processed_count")
	r.Progress = field.NewFloat64(table, "progress")
	r.PreviewTotal = field.NewInt64(table, "preview_total")
	r.ResultRecordID = field.NewString(table, "result_record_id")
	r.Error = field.NewString(table, "error")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.AnalysisMode = field.NewString(table, "analysis_mode")

	r.fillFieldMap()

	return r
}

func (r *recordAnalysisJob) WithContext(ctx context.Context) IRecordAnalysisJobDo {
	return r.recordAnalysisJobDo.WithContext(ctx)
}

func (r recordAnalysisJob) TableName() string { return r.recordAnalysisJobDo.TableName() }

func (r recordAnalysisJob) Alias() string { return r.recordAnalysisJobDo.Alias() }

func (r recordAnalysisJob) Columns(cols ...field.Expr) gen.Columns {
	return r.recordAnalysisJobDo.Columns(cols...)
}

func (r *recordAnalysisJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *recordAnalysisJob) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 16)
	r.fieldMap["id"] = r.ID
	r.fieldMap["status"] = r.Status
	r.fieldMap["stage"] = r.Stage
	r.fieldMap["relationship_id"] = r.RelationshipID
	r.fieldMap["file_name"] = r.FileName
	r.fieldMap["message_count"] = r.MessageCount
	r.fieldMap["llm_message_limit"] = r.LlmMessageLimit
	r.fieldMap["llm_message_count"] = r.LlmMessageCount
	r.fieldMap["processed_count"] = r.ProcessedCount
	r.fieldMap["progress"] = r.Progress
	r.fieldMap["preview_total"] = r.PreviewTotal
	r.fieldMap["result_record_id"] = r.ResultRecordID
	r.fieldMap["error"] = r.Error
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["analysis_mode"] = r.AnalysisMode
}

func (r recordAnalysisJob) clone(db *gorm.DB) recordAnalysisJob {
	r.recordAnalysisJobDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r recordAnalysisJob) replaceDB(db *gorm.DB) recordAnalysisJob {
	r.recordAnalysisJobDo.ReplaceDB(db)
	return r
}

type recordAnalysisJobDo struct {
	gen.GenericsDo[IRecordAnalysisJobDo, *model.RecordAnalysisJob]
}
type IRecordAnalysisJobDo interface {
	gen.IGenericsDo[IRecordAnalysisJobDo, *model.RecordAnalysisJob]
}

func (r *recordAnalysisJobDo) withDO(do gen.Dao) IRecordAnalysisJobDo {
	_r := &recordAnalysisJobDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRecordAnalysisJobDo](r.withDO)
	return _r
}
