// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/kevinmatthe/record_analysis/internal/infrastructure/db/model"
)

func newRecordAnalysisJobMessage(db *gorm.DB, opts ...gen.DOOption) recordAnalysisJobMessage {
	_recordAnalysisJobMessage := recordAnalysisJobMessage{}

	_recordAnalysisJobMessage.recordAnalysisJobMessageDo.IWithDO = gen.WithDOFunc[IRecordAnalysisJobMessageDo](_recordAnalysisJobMessage.recordAnalysisJobMessageDo.withDO)

	_recordAnalysisJobMessage.recordAnalysisJobMessageDo.UseDB(db, opts...)
	_recordAnalysisJobMessage.recordAnalysisJobMessageDo.UseModel(&model.RecordAnalysisJobMessage{})

	tableName := _recordAnalysisJobMessage.recordAnalysisJobMessageDo.TableName()
	_recordAnalysisJobMessage.ALL = field.NewAsterisk(tableName)
	_recordAnalysisJobMessage.ID = field.NewInt64(tableName, "id")
	_recordAnalysisJobMessage.JobID = field.NewString(tableName, "job_id")
	_recordAnalysisJobMessage.Seq = field.NewInt64(tableName, "seq")
	_recordAnalysisJobMessage.MsgID = field.NewString(tableName, "msg_id")
	_recordAnalysisJobMessage.Sender = field.NewString(tableName, "sender")
	_recordAnalysisJobMessage.MsgTime = field.NewTime(tableName, "msg_time")
	_recordAnalysisJobMessage.MsgType = field.NewString(tableName, "msg_type")
	_recordAnalysisJobMessage.Content = field.NewString(tableName, "content")
	_recordAnalysisJobMessage.CreatedAt = field.NewTime(tableName, "created_at")

	_recordAnalysisJobMessage.fillFieldMap()

	return _recordAnalysisJobMessage
}

type recordAnalysisJobMessage struct {
	recordAnalysisJobMessageDo recordAnalysisJobMessageDo

	ALL       field.Asterisk
	ID        field.Int64
	JobID     field.String
	Seq       field.Int64
	MsgID     field.String
	Sender    field.String
	MsgTime   field.Time
	MsgType   field.String
	Content   field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (r recordAnalysisJobMessage) Table(newTableName string) *recordAnalysisJobMessage {
	r.recordAnalysisJobMessageDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r recordAnalysisJobMessage) As(alias string) *recordAnalysisJobMessage {
	r.recordAnalysisJobMessageDo.DO = *(r.recordAnalysisJobMessageDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *recordAnalysisJobMessage) updateTableName(table string) *recordAnalysisJobMessage {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.JobID = field.NewString(table, "job_id")
	r.Seq = field.NewInt64(table, "seq")
	r.MsgID = field.NewString(table, "msg_id")
	r.Sender = field.NewString(table, "sender")
	r.MsgTime = field.NewTime(table, "msg_time")
	r.MsgType = field.NewString(table, "msg_type")
	r.Content = field.NewString(table, "content")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *recordAnalysisJobMessage) WithContext(ctx context.Context) IRecordAnalysisJobMessageDo {
	return r.recordAnalysisJobMessageDo.WithContext(ctx)
}

func (r recordAnalysisJobMessage) TableName() string { return r.recordAnalysisJobMessageDo.TableName() }

func (r recordAnalysisJobMessage) Alias() string { return r.recordAnalysisJobMessageDo.Alias() }

func (r recordAnalysisJobMessage) Columns(cols ...field.Expr) gen.Columns {
	return r.recordAnalysisJobMessageDo.Columns(cols...)
}

func (r *recordAnalysisJobMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *recordAnalysisJobMessage) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 9)
	r.fieldMap["id"] = r.ID
	r.fieldMap["job_id"] = r.JobID
	r.fieldMap["seq"] = r.Seq
	r.fieldMap["msg_id"] = r.MsgID
	r.fieldMap["sender"] = r.Sender
	r.fieldMap["msg_time"] = r.MsgTime
	r.fieldMap["msg_type"] = r.MsgType
	r.fieldMap["content"] = r.Content
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r recordAnalysisJobMessage) clone(db *gorm.DB) recordAnalysisJobMessage {
	r.recordAnalysisJobMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r recordAnalysisJobMessage) replaceDB(db *gorm.DB) recordAnalysisJobMessage {
	r.recordAnalysisJobMessageDo.ReplaceDB(db)
	return r
}

type recordAnalysisJobMessageDo struct {
	gen.GenericsDo[IRecordAnalysisJobMessageDo, *model.RecordAnalysisJobMessage]
}
type IRecordAnalysisJobMessageDo interface {
	gen.IGenericsDo[IRecordAnalysisJobMessageDo, *model.RecordAnalysisJobMessage]
}

func (r *recordAnalysisJobMessageDo) withDO(do gen.Dao) IRecordAnalysisJobMessageDo {
	_r := &recordAnalysisJobMessageDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRecordAnalysisJobMessageDo](r.withDO)
	return _r
}
