// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/kevinmatthe/record_analysis/internal/infrastructure/db/model"
)

func newRecordAnalysisUser(db *gorm.DB, opts ...gen.DOOption) recordAnalysisUser {
	_recordAnalysisUser := recordAnalysisUser{}

	_recordAnalysisUser.recordAnalysisUserDo.IWithDO = gen.WithDOFunc[IRecordAnalysisUserDo](_recordAnalysisUser.recordAnalysisUserDo.withDO)

	_recordAnalysisUser.recordAnalysisUserDo.UseDB(db, opts...)
	_recordAnalysisUser.recordAnalysisUserDo.UseModel(&model.RecordAnalysisUser{})

	tableName := _recordAnalysisUser.recordAnalysisUserDo.TableName()
	_recordAnalysisUser.ALL = field.NewAsterisk(tableName)
	_recordAnalysisUser.ID = field.NewString(tableName, "id")
	_recordAnalysisUser.Username = field.NewString(tableName, "username")
	_recordAnalysisUser.PasswordHash = field.NewString(tableName, "password_hash")
	_recordAnalysisUser.CreatedAt = field.NewTime(tableName, "created_at")
	_recordAnalysisUser.UpdatedAt = field.NewTime(tableName, "updated_at")

	_recordAnalysisUser.fillFieldMap()

	return _recordAnalysisUser
}

type recordAnalysisUser struct {
	recordAnalysisUserDo recordAnalysisUserDo

	ALL          field.Asterisk
	ID           field.String
	Username     field.String
	PasswordHash field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (r recordAnalysisUser) Table(newTableName string) *recordAnalysisUser {
	r.recordAnalysisUserDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r recordAnalysisUser) As(alias string) *recordAnalysisUser {
	r.recordAnalysisUserDo.DO = *(r.recordAnalysisUserDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *recordAnalysisUser) updateTableName(table string) *recordAnalysisUser {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.Username = field.NewString(table, "username")
	r.PasswordHash = field.NewString(table, "password_hash")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *recordAnalysisUser) WithContext(ctx context.Context) IRecordAnalysisUserDo {
	return r.recordAnalysisUserDo.WithContext(ctx)
}

func (r recordAnalysisUser) TableName() string { return r.recordAnalysisUserDo.TableName() }

func (r recordAnalysisUser) Alias() string { return r.recordAnalysisUserDo.Alias() }

func (r recordAnalysisUser) Columns(cols ...field.Expr) gen.Columns {
	return r.recordAnalysisUserDo.Columns(cols...)
}

func (r *recordAnalysisUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *recordAnalysisUser) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 5)
	r.fieldMap["id"] = r.ID
	r.fieldMap["username"] = r.Username
	r.fieldMap["password_hash"] = r.PasswordHash
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r recordAnalysisUser) clone(db *gorm.DB) recordAnalysisUser {
	r.recordAnalysisUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r recordAnalysisUser) replaceDB(db *gorm.DB) recordAnalysisUser {
	r.recordAnalysisUserDo.ReplaceDB(db)
	return r
}

type recordAnalysisUserDo struct {
	gen.GenericsDo[IRecordAnalysisUserDo, *model.RecordAnalysisUser]
}
type IRecordAnalysisUserDo interface {
	gen.IGenericsDo[IRecordAnalysisUserDo, *model.RecordAnalysisUser]
}

func (r *recordAnalysisUserDo) withDO(do gen.Dao) IRecordAnalysisUserDo {
	_r := &recordAnalysisUserDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRecordAnalysisUserDo](r.withDO)
	return _r
}
