// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRecordAnalysisJobEvent = "record_analysis_job_events"

// RecordAnalysisJobEvent mapped from table <record_analysis_job_events>
type RecordAnalysisJobEvent struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	JobID     string    `gorm:"column:job_id;not null" json:"job_id"`
	Message   string    `gorm:"column:message;not null" json:"message"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName RecordAnalysisJobEvent's table name
func (*RecordAnalysisJobEvent) TableName() string {
	return TableNameRecordAnalysisJobEvent
}
