// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRecordAnalysisRecord = "record_analysis_records"

// RecordAnalysisRecord mapped from table <record_analysis_records>
type RecordAnalysisRecord struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`
	RelationshipID string    `gorm:"column:relationship_id;not null" json:"relationship_id"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	PeriodStart    time.Time `gorm:"column:period_start" json:"period_start"`
	PeriodEnd      time.Time `gorm:"column:period_end" json:"period_end"`
	MessageCount   int64     `gorm:"column:message_count;not null" json:"message_count"`
	ActionCount    int64     `gorm:"column:action_count;not null" json:"action_count"`
	EventCount     int64     `gorm:"column:event_count;not null" json:"event_count"`
	ModelName      string    `gorm:"column:model_name;not null" json:"model_name"`
	ObjectKey      string    `gorm:"column:object_key;not null" json:"object_key"`
	ObjectURI      string    `gorm:"column:object_uri;not null" json:"object_uri"`
	ReportPath     string    `gorm:"column:report_path;not null" json:"report_path"`
	Status         string    `gorm:"column:status;not null" json:"status"`
}

// TableName RecordAnalysisRecord's table name
func (*RecordAnalysisRecord) TableName() string {
	return TableNameRecordAnalysisRecord
}
