// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRecordAnalysisUser = "record_analysis_users"

// RecordAnalysisUser mapped from table <record_analysis_users>
type RecordAnalysisUser struct {
	ID           string    `gorm:"column:id;primaryKey" json:"id"`
	Username     string    `gorm:"column:username;not null" json:"username"`
	PasswordHash string    `gorm:"column:password_hash;not null" json:"password_hash"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName RecordAnalysisUser's table name
func (*RecordAnalysisUser) TableName() string {
	return TableNameRecordAnalysisUser
}
