// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRecordAnalysisJobMessage = "record_analysis_job_messages"

// RecordAnalysisJobMessage mapped from table <record_analysis_job_messages>
type RecordAnalysisJobMessage struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	JobID     string    `gorm:"column:job_id;not null" json:"job_id"`
	Seq       int64     `gorm:"column:seq;not null" json:"seq"`
	MsgID     string    `gorm:"column:msg_id;not null" json:"msg_id"`
	Sender    string    `gorm:"column:sender;not null" json:"sender"`
	MsgTime   time.Time `gorm:"column:msg_time;not null" json:"msg_time"`
	MsgType   string    `gorm:"column:msg_type;not null" json:"msg_type"`
	Content   string    `gorm:"column:content;not null" json:"content"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName RecordAnalysisJobMessage's table name
func (*RecordAnalysisJobMessage) TableName() string {
	return TableNameRecordAnalysisJobMessage
}
