// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRecordAnalysisJob = "record_analysis_jobs"

// RecordAnalysisJob mapped from table <record_analysis_jobs>
type RecordAnalysisJob struct {
	ID              string    `gorm:"column:id;primaryKey" json:"id"`
	Status          string    `gorm:"column:status;not null" json:"status"`
	Stage           string    `gorm:"column:stage;not null" json:"stage"`
	RelationshipID  string    `gorm:"column:relationship_id;not null" json:"relationship_id"`
	FileName        string    `gorm:"column:file_name;not null" json:"file_name"`
	MessageCount    int64     `gorm:"column:message_count;not null" json:"message_count"`
	LlmMessageLimit int64     `gorm:"column:llm_message_limit;not null" json:"llm_message_limit"`
	LlmMessageCount int64     `gorm:"column:llm_message_count;not null" json:"llm_message_count"`
	ProcessedCount  int64     `gorm:"column:processed_count;not null" json:"processed_count"`
	Progress        float64   `gorm:"column:progress;not null" json:"progress"`
	PreviewTotal    int64     `gorm:"column:preview_total;not null" json:"preview_total"`
	ResultRecordID  string    `gorm:"column:result_record_id;not null" json:"result_record_id"`
	Error           string    `gorm:"column:error;not null" json:"error"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	AnalysisMode    string    `gorm:"column:analysis_mode;not null;default:full" json:"analysis_mode"`
}

// TableName RecordAnalysisJob's table name
func (*RecordAnalysisJob) TableName() string {
	return TableNameRecordAnalysisJob
}
