// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRecordAnalysisSession = "record_analysis_sessions"

// RecordAnalysisSession mapped from table <record_analysis_sessions>
type RecordAnalysisSession struct {
	Token     string    `gorm:"column:token;primaryKey" json:"token"`
	Username  string    `gorm:"column:username;not null" json:"username"`
	ExpiresAt time.Time `gorm:"column:expires_at;not null" json:"expires_at"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName RecordAnalysisSession's table name
func (*RecordAnalysisSession) TableName() string {
	return TableNameRecordAnalysisSession
}
